
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Reproducible Research: Peer Assessment 1 

## Loading and preprocessing the data

```{r activity}
dane <- read.csv('activity.csv')
head(dane)
str(dane)
```

## What is mean total number of steps taken per day?

```{r hist}
steps_per_d <- tapply(dane$steps, dane$date, sum)
hist(steps_per_d, col = "green")
mean_steps_per_d <- mean(steps_per_d, na.rm = TRUE)
median_steps_per_d <- median(steps_per_d, na.rm = TRUE)
print(mean_steps_per_d)
print(median_steps_per_d)
```

## What is the average daily activity pattern?

```{r plot}
rob <- dane[!is.na(dane$steps),]
avg_steps_per_int <- tapply(rob$steps, rob$interval, mean)

dim(avg_steps_per_int)
num_of_int <- dim(dane)[1]/(31+30)
num_of_int

plot(x=dane$interval[1:288], y=avg_steps_per_int, type = "l", xlab = "Interval")
max(avg_steps_per_int)
which.max(avg_steps_per_int)
```

## Imputing missing values

```{r}
summary(dane)
head(!complete.cases(dane))
head(dane[!complete.cases(dane), ])
```

### Proxy missing values with median_steps_per_d/num_of_int

```{r}
new_data <- dane
new_data[is.na(new_data$steps),"steps"] <- median_steps_per_d/num_of_int
```

### check:
```{r proxy_hist}
any(is.na(new_data))
new_data[1:5,]

new_steps_per_d <- tapply(new_data$steps, new_data$date, sum)
hist(new_steps_per_d, col = "green")
mean_new_steps_per_d <- mean(new_steps_per_d)
median_new_steps_per_d <- median(new_steps_per_d)
print(mean_new_steps_per_d)
print(median_new_steps_per_d)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r proxy_plot}
library(lubridate)

rob2 <- wday(as.Date(new_data$date)) # 1 = Sunday, 2 = Monday, 3 = Tuesday, etc.

for (i in 1:dim(new_data)[1]) {
    if(rob2[i] == 7 | rob2[i] == 1) {
        new_data$weekdays[i] <- "weekend"
    } else {
        new_data$weekdays[i] <- "weekday" 
    } 
}

head(new_data)
new_data$weekdays <- as.factor(new_data$weekdays)

table(new_data$weekdays)
table(new_data$weekdays)/288

rob3 <- new_data[new_data$weekdays=="weekend",]
avg_weekend <- tapply(rob3$steps, rob3$interval, mean)
rob4 <- new_data[new_data$weekdays=="weekday",]
avg_weekday <- tapply(rob4$steps, rob4$interval, mean)
x <- c(new_data$interval[1:288], new_data$interval[1:288])
y <- c(avg_weekend, avg_weekday)
f <- as.factor(c(rep("weekend", 288), rep("weekday", 288)))

library(lattice)

xyplot(y ~ x | f, layout=c(1,2), type = "l", lwd = 2, xlab = "Interval", 
       ylab = "Number of steps")
```

